version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: yad2_vehicles
      POSTGRES_USER: yad2_user
      POSTGRES_PASSWORD: yad2_p4ss$
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yad2_user -d yad2_vehicles"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
